force-app/main/default/objects/SpotifySettings__c/SpotifySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Spotify Settings</label>
</CustomObject>

force-app/main/default/objects/SpotifySettings__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>Client Id of Spotify App</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpotifySettings__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>Client secret from Spotify app</description>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tests/OAuthRedirectTest.cls
@isTest
private with sharing class OAuthRedirectTest {
    @testSetup
    static void setupData() {
        TestUtils.createSpotifyUser();
    }

    @isTest
    static void testGetToken() {
        User u = [SELECT Id FROM User WHERE Email = :TestUtils.UNIT_TEST_EMAIL LIMIT 1];
        System.runAs(u) {
            SpotifySettings__c settings = SpotifySettings__c.getInstance();
            settings.State__c = 'abc';
            settings.ClientId__c = 'client';
            settings.ClientSecret__c = 'secret';
            upsert settings;

            PageReference pageRef = Page.oauthRedirect;
            pageRef.getParameters().put('code', '123');
            pageRef.getParameters().put('state', 'abc');
            Test.setCurrentPage(pageRef);

            String response = '{"access_token":"access","refresh_token":"refresh"}';
            HttpCalloutMockFactory mock = new HttpCalloutMockFactory(200, 'success', response, null);
            Test.setMock(HttpCalloutMock.class, mock);

            Test.startTest();
            OAuthRedirectController controller = new OAuthRedirectController();
            controller.getToken();
            Test.stopTest();

            SpotifySettings__c updatedSettings = SpotifySettings__c.getInstance();
            Assert.areEqual('access', updatedSettings.AccessToken__c, 'Access token should be updated');
            Assert.areEqual('refresh', updatedSettings.RefreshToken__c, 'Refresh token should be updated');
        }
    }
}