force-app/main/default/objects/SpotifySettings__c/SpotifySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Spotify Settings</label>
</CustomObject>

force-app/main/default/objects/SpotifySettings__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>Client Id of Spotify App</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpotifySettings__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>Client secret from Spotify app</description>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tests/SpotifyAuthorizeControllerTest.cls
@isTest
private with sharing class SpotifyAuthorizeControllerTest {
    @testSetup
    private static void setupData() {
        TestUtils.createSpotifyUser();
        User u = [SELECT Id FROM User WHERE Email = :TestUtils.UNIT_TEST_EMAIL LIMIT 1];
        System.runAs(u) {
            SpotifySettings__c settings = SpotifySettings__c.getInstance();
            settings.ClientId__c = 'client';
            settings.ClientSecret__c = 'secret';
            settings.AccessToken__c = 'access';
            upsert settings;
        }
    }

    @isTest
    static void testCheckAuthorization() {
        User u = [SELECT Id FROM User WHERE Email = :TestUtils.UNIT_TEST_EMAIL LIMIT 1];
        System.runAs(u) {
            Test.startTest();
            Boolean authorized = SpotifyAuthorizeController.checkAuthorization();
            Test.stopTest();

            Assert.isTrue(authorized, 'Should be authorized');
        }
    }

    @isTest
    static void testAuthorize() {
        User u = [SELECT Id FROM User WHERE Email = :TestUtils.UNIT_TEST_EMAIL LIMIT 1];
        System.runAs(u) {
            Test.startTest();
            String authUrl = SpotifyAuthorizeController.authorize('updatedClient', 'updatedSecret');
            Test.stopTest();

            Assert.isTrue(authUrl.contains('updatedClient'), 'Should include client id');

            SpotifySettings__c settings = SpotifySettings__c.getInstance();
            Assert.areEqual('updatedClient', settings.ClientId__c, 'Client Id should be updated');
            Assert.areEqual('updatedSecret', settings.ClientSecret__c, 'Client Secret should be updated');
        }
    }

    @isTest
    static void testReset() {
        User u = [SELECT Id FROM User WHERE Email = :TestUtils.UNIT_TEST_EMAIL LIMIT 1];
        System.runAs(u) {
            Test.startTest();
            SpotifyAuthorizeController.resetAuthorization();
            Test.stopTest();

            SpotifySettings__c settings = SpotifySettings__c.getInstance();
            Assert.isNull(settings.ClientId__c, 'Should be deleted');
        }
    }
}