force-app/main/default/objects/SpotifyEndpointSetting__mdt/SpotifyEndpointSetting__mdt.object-meta.xml
<CustomObject>
    <description>Holds endpoints used in Spotify integration</description>
    <label>Spotify Endpoint Setting</label>
    <pluralLabel>Spotify Endpoint Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SpotifyEndpointSetting__mdt/fields/AccountsEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AccountsEndpoint__c</fullName>
    <label>Accounts Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SpotifySettings__c/SpotifySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Spotify Settings</label>
</CustomObject>

force-app/main/default/objects/SpotifySettings__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>Client Id of Spotify App</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpotifySettings__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>Client secret from Spotify app</description>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SpotifyAuthorizeController.cls
public with sharing class SpotifyAuthorizeController {
    @AuraEnabled
    public static Boolean checkAuthorization() {
        SpotifySettings__c settings = SpotifySettings__c.getInstance();
        return settings.AccessToken__c != null;
    }

    @AuraEnabled
    public static String authorize(String clientId, String clientSecret) {
        try {
            SpotifySettings__c settings = SpotifySettings__c.getInstance();
            settings.ClientId__c = clientId;
            settings.clientSecret__c = clientSecret;

            String state = String.valueOf(Crypto.getRandomInteger());
            settings.State__c = state;
            upsert as system settings;

            String vfUrl = URL.getOrgDomainUrl().toExternalForm() + '/apex/oauthRedirect';

            SpotifyEndpointSetting__mdt setting = SpotifyEndpointSetting__mdt.getInstance('Default');
            String authUrl =
                setting.AccountsEndpoint__c +
                '/authorize?client_id=' +
                clientId +
                '&response_type=code&redirect_uri=' +
                vfUrl +
                '&state=' +
                state +
                '&scope=user-read-private user-read-email';

            return authUrl;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void resetAuthorization() {
        try {
            SpotifySettings__c settings = SpotifySettings__c.getInstance();
            delete as system settings;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}